on:
  push:
    branches: [ main ]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0
      - name: Create local changes
        run: |
            date > generated.txt
            ls -ls
            cat generated.txt
      - name: Commit files
        run: |
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: ${{ github.ref }}
      - name: Push changes
        uses: actions-go/push@v1
        with:
          # The email that will appear in commits when changes needs to be committed
          author-email: babirali001@gmail.com
          author-name: babirali
          commit-message: test
          token: ${{ secrets.PUSH_TOKEN }}
