name: Publish package to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    # - name: Deploy to Github Package Registry
    #   env:
    #     GITHUB_USERNAME: x-access-token
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     GITHUB_REPOSITORY: ${{ github.repository }}
    #   run:
    #     mvn deploy
    - name: Publish artifact to github packages.
      run: |
        echo $GROUP
        echo $OWNER
        echo $REPOSITORY
        curl -i -X PUT \
        "https://maven.pkg.github.com/$OWNER/$REPOSITORY/$GROUP/github/com.mycompany.app.my-app/master/2/pom" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "rewrite: 1" \
        --upload-file "./pom.xml" -vvv