# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          echo 'bravo'    > bravo.html
          echo 'charlie'  > charlie.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
      - name: Trigger Azure Release Pipelines
        uses: Azure/pipelines@release/v1
        with: 
          azure-devops-project-url: https://dev.azure.com/ahcs-dev/MHS
          azure-pipeline-name: Test
          azure-devops-token: c2ji5e22hm43bg32m7tmdg3syyqnnnrzwiyadigiyrpei6vtnfxq
